#
# Module manifest for module 'Hallisters Standard'
#
# Generated by: Chad Hall
#
# Generated on: 4/2/2025
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '0.0.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '94e38dcc-0516-4975-bfdf-a0542edf92f9'

# Author of this module
Author = 'Chad Hall'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) Chad Hall. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This module is a set of tools used regularly in various areas. This module was written in order to improve scripts by decreasing the amount of repetitive code.

Included Functions:
-Show-UninstallRegistry
    Description:
        This function will scour both the 32-bit and 64-bit registry uninstall keys. This will show all installed applications as they appear in the registry as well as any details.
    Usage:M
        Basic Details: Show-UninstallRegistry -NameToFind ''citrix''
        All Details: Show-UninstallRegistry -NameToFind ''citrix'' -ShowDetails

-Get-OSArchitecture
    Description:
        A simple function to determine if the machine is a 32-bit or 64-bit operating system
    Useage:
        Get-OSArchitecture
    Output:
        Either 32-Bit CPU or 64-Bit CPU

-Write-CustomLog
    Description:
        This is an all inclusive function for the writing of logs. The only code you will need in your script is the below usage code to writ the file.
        The Type can use one of the following options:
            Error
            Warning
            Info
    Usage:
        Write-CustomLog -Message ''MESSAGEHERE'' -Type ''Info'' -LogDir ''C:\Windows\Temp\'' -LogFile ''TestLog.log''

-Open-File
    Description:
        This function will present you with a file open dialog box. This is useful for when you need to open a file but do not know the path.
    Usage:
        $FileSelected = Open-File

-Invoke-AnyKeyToContinue
    Description:
        This function is a simple function to wait for user input before continuing.
    Usage:
        Invoke-AnyKeyToContinue

-Publish-ActiveSetup
    Description:
        This function will publish an active setup key to the registry. This is useful for when you need to run a script or program on the next logon.
    Usage:
        Publish-ActiveSetup -ActiveSetupName "Test" -VersionNumber "1" -ActiveSetupStubPath "EXE or SCRIPT YOU WANT TO RUN"

-Set-NetworkAsPrivate
    Description:
        This function will set the network type to private if a name is supplied. If a name is not supplied you will recieve a list of all network names.
    Usage:
        Set-NetworkAsPrivate
        Set-NetworkAsPrivate -NetworkConnectionName "NetworkName"

-Invoke-FileSystemRepair
    Description:
        This function will run several file system repair tools. This includes:
            -sfc /scannow
            -dism /online /cleanup-image /CheckHealth
            -dism /online /cleanup-image /ScanHealth
            -dism /online /cleanup-image /startcomponentcleanup
            -dism /online /cleanup-image /restorehealth
    Usage:
        Invoke-FileSystemRepair

-Invoke-SCCMActions
    Description:
        This function will run several SCCM actions. This includes:
            -Machine policy retrieval & Evaluation Cycle
            -Application deployment evaluation cycle
            -Software inventory cycle
        If you add the -ClearCache switch it will also clear the SCCM cache before running the above commands.
    Usage:
        Invoke-SCCMActions

-Invoke-RemoteSCCMActions
    Description:
        This function will run several SCCM actions on a remote machine. This includes:
            -Machine Policy Evaluation Cycle
            -Application Deployment Evaluation Cycle
            -Software Inventory Cycle
    Usage:
        Invoke-RemoteSCCMActions -ComputerName "COMPUTERNAME"

        $ComputerList = Get-Content -Path "C:\ComputerList.txt"
        ForEach ($Computer in $ComputerList) {
            Invoke-RemoteSCCMActions -ComputerName $Computer
        }

-Invoke-AddPermissions
    Description:
        This function will ask for some information and set permissions accordingly.
    Usage:
'

# Minimum version of the PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

